### ISSUE TITLE
Code up new public-facing pages 

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#672] opened 2015-06-08 18:22 UTC
We have new designs for the public-facing pages (aka landing page and Learn More). Basic mockups [here](https://projects.invisionapp.com/d/main#/console/2318574/82558831/preview). 

cc @juliaelman

**Comment by esgoodman** [comment] 2015-06-08 20:11
Moved to backlog to prioritize working on sign-in flow.

**Comment by jackiekazil** [comment] 2015-07-06 18:18
@juliaelman -- is this a dupe of something else? (I feel like this might already exist and you are working on it?)

**Comment by juliaelman** [comment] 2015-07-06 18:26
@jackiekazil I could not find a dupe of this in the existing open issues. AFAIK, this is on hold to prioritize the sign in flow work.

@esgoodman @mkhandekar are there completed/finalized screens for the updated landing and learn more pages? If so, would you mind adding the final version of those to this issue?

**Comment by juliaelman** [comment] 2015-08-03 18:23
@jackiekazil @esgoodman @mkhandekar should we leave this open or close?

**Comment by esgoodman** [comment] 2015-08-03 21:13
Let's close it. Superceded by #723.

**Comment by jackiekazil** [comment] 2015-08-03 22:53
:+1:

**Closed by jackiekazil** 2015-08-03 22:53 UTC
Labels: 1-backlog, task, _develop
