### ISSUE TITLE
Authentication link goes to HTTP destination first

### ISSUE THREAD

**Issue by konklone** [18F/myusa#650] opened 2015-05-14 04:34 UTC
When clicking the authentication link I've been sent, after traveling through the Mandrill redirector as documented in #649, the redirect is first to an HTTP URL, `http://alpha.my.usa.gov`.

I've modified the links below to use `XXXXXX` instead of full tokens:

```
$ curl --head "http://mandrillapp.com/track/click/30288227/alpha.my.usa.gov?p=XXXXXX"

HTTP/1.0 302 Moved Temporarily
X-TurboPage: Direct
Server: nginx/1.6.2
Date: Thu, 14 May 2015 04:27:21 GMT
Content-Type: text/html; charset=utf-8
Set-Cookie: PHPSESSID=c3564d91da2ae38935d9f7eb74a11514; path=/
Pragma: no-cache
Location: http://alpha.my.usa.gov/users/sign_in?email=eric.mill%40gsa.gov&token=XXX
```

The alpha.my.usa.gov link then redirects to HTTPS. `https://alpha.my.usa.gov` doesn't have a HSTS header set, but even if it did, not all clients support HSTS (Internet Explorer still doesn't support it).

Like #649, this is another domain which, if it were targeted for attack on a network, would subject me to tracking or redirection attacks. I'm assuming MyUSA's security model protects against replay attacks.

**Comment by mbland** [comment] 2015-05-15 21:27
Also, #573.

**Comment by NoahKunin** [comment] 2015-06-05 23:19
Just confirming this a must fix, hostile networks are very real.

**Comment by konklone** [comment] 2015-06-11 19:36
From https://github.com/18F/myusa/issues/573#issuecomment-111225286:

> This should be fixed in 8fc9a1d. A related issue was Mandrill was rewriting all email links to do clickthrough tracking and that has also been disabled.

**Comment by yozlet** [comment] 2015-06-15 17:43
Fixed in #674, merged.

**Comment by jackiekazil** [comment] 2015-06-15 19:23
@konklone Can you do the accept?

**Comment by yozlet** [comment] 2015-06-15 19:34
Note that this fix is currently live on Old (AWS) Staging ( https://myusa-staging.18f.us/ ) but not production (alpha)

**Comment by konklone** [comment] 2015-06-15 21:04
@yozlet Has staging been updated with the merged work in #674? I just tried the flow on the staging site, and got an email where the link click was to a `http://myusa-staging.18f.us` URL. 

```
$ curl --head "http://myusa-staging.18f.us/users/sign_in?email=eric.mill%40gsa.gov&token=RYdhB-E4Kt4RCseyA_nP"

HTTP/1.1 301 Moved Permanently
Content-Length: 178
Content-Type: text/html
Date: Mon, 15 Jun 2015 21:01:32 GMT
Location: https://myusa-staging.18f.us/users/sign_in?email=eric.mill%40gsa.gov&token=RYdhB-E4Kt4RCseyA_nP
Server: nginx
Connection: keep-alive
```

Because the solution to #649 was to remove the `mandrillapp.com` redirector entirely, I'm honestly not sure how to evaluate #649 and #650 separately anymore. However, both issues reference fixes which have either been deployed or merged into staging, and the above shows that at least one of them is not done on staging.

**Comment by yozlet** [comment] 2015-06-18 18:36
Sorry - looks like certain fixes didn't get auto-deployed to Old Staging as I thought they would. However, it's definitely fixed on New Staging (just tested).

**Comment by konklone** [comment] 2015-06-18 23:03
I can confirm that this is fixed on `staging.my.usa.gov`. :+1:

**Comment by harrisj** [comment] 2015-06-18 23:08
Can we close this issue then?

Sent from my iPhone

On Jun 18, 2015, at 7:03 PM, Eric Mill <notifications@github.com> wrote:

I can confirm that this is fixed on staging.my.usa.gov. [image: :+1:]

—
Reply to this email directly or view it on GitHub
<https://github.com/18F/myusa/issues/650#issuecomment-113311946>.

**Comment by jackiekazil** [comment] 2015-06-18 23:28
We CAN!

**Closed by jackiekazil** 2015-06-18 23:28 UTC
Labels: 5-accept, p1
