### ISSUE TITLE
GSA users are not able to login to MyUSA on a mobile device

### ISSUE THREAD

**Issue by phirefly** [18F/myusa#690] opened 2015-06-23 20:43 UTC
When logging in through a mobile browser, a GSA user that authenticates with their ENT password cannot login with MyUSA. After entering their password, they are brought back to the login page (the page with the Login with Google button)

Found on iPhone + Safari (not tested on Android)

**Comment by adelevie** [comment] 2015-06-23 20:46
FWIW, I could log in on my Android.

**Comment by phirefly** [comment] 2015-06-23 20:47
@adelevie I'm assuming Chrome?

**Comment by adelevie** [comment] 2015-06-23 20:49
Yep. Most importantly, I feel that this issue lies with the way GSA authenticates users for Google Apps and is largely our of MyUSA control.

Can users log in with their email addressed instead?

**Comment by phirefly** [comment] 2015-06-23 20:56
yes, sorry, updating the story. Not able to auth with MyUSA to our app at c2-staging.18f.gov

**Comment by phirefly** [comment] 2015-06-23 21:01
Success on Chrome + iOS for me

**Comment by harrisj** [comment] 2015-07-14 17:23
@phirefly Just to clarify this one, are you trying to log into MyUSA (to see your account for instance), or log in to another app on mobile via MyUSA (ie, _authorization_)?

**Comment by harrisj** [comment] 2015-07-21 15:05
> When logging in through a mobile browser, a GSA user that authenticates with their ENT password cannot login with MyUSA. After entering their password, they are brought back to the login page (the page with the Login with Google button)

Sorry, I just tried this and it worked for me now, but I see the problem described above. The issue is that sometimes the GSA authentication does not allow mobile logins from Google (I've experienced trying to setup third-party calendar apps on my phone). I'm not sure if we should not even show the Google login, but this is outside the scope of what we can do within MyUSA. Closing it for now unless someone thinks we should reopen.

**Closed by harrisj** 2015-07-21 15:05 UTC
Labels: 3-working, p2
