### ISSUE TITLE
Raphy's GSA account doesn't follow app redirects on login in certain browsers

### ISSUE THREAD

**Issue by yozlet** [18F/myusa#693] opened 2015-06-26 21:47 UTC
@phirefly is trying to sign in to [c2-staging](https://c2-staging.18f.gov/) using different iOS browsers. On Safari, when using email login (not Google) to c2-staging, his sign in process drops him out _not_ at the c2 front page as intended, but at the MyUSA "Personal Details" page. When he logs in with his personal email, it takes him to the c2 front page. Why?

**Comment by jackiekazil** [comment] 2015-06-29 17:31
Possibly related? but not certain -- #690  (according to Yoz)

**Comment by harrisj** [comment] 2015-07-21 14:53
> On Safari, when using email login (not Google) to c2-staging, his sign in process drops him out not at the c2 front page as intended, but at the MyUSA "Personal Details" page.

I just tried this and it took me through to Communicart front page. I can't reproduce right now. Closing, but please open if issue seems to have reappeared.

**Closed by harrisj** 2015-07-21 14:53 UTC
Labels: bug, p2

**Comment by esgoodman** [comment] 2015-07-21 16:16
Should we try to add some guidance in an error message? I hate leaving
people thinking that it's MyUSA when actually it's a GSA thing that we
don't control.
